# Generated by Django 3.2.10 on 2023-12-18 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nursery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название питомника')),
                ('location', models.CharField(max_length=100, verbose_name='Местоположение питомника')),
                ('phone', models.CharField(max_length=21, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Питомник',
                'verbose_name_plural': 'Питомники',
                'db_table': 'nurseries',
            },
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('type_pet', models.CharField(choices=[('C', 'Кошка'), ('D', 'Собака'), ('R', 'Грызун'), ('B', 'Птица'), ('RT', 'Рептилия'), ('I', 'Насекомое')], max_length=2, verbose_name='Вид животного')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('breed', models.CharField(default=None, max_length=25, verbose_name='Порода')),
                ('is_male', models.BooleanField(default=True, verbose_name='Самец')),
                ('photo', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=150)),
                ('nursery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='loader.nursery', verbose_name='Питомник')),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': 'Питомцы',
                'db_table': 'pets',
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('preview', models.ImageField(blank=True, upload_to='')),
                ('middle', models.ImageField(blank=True, upload_to='')),
                ('priority', models.SmallIntegerField(default=0)),
                ('data', models.DateField(auto_now_add=True)),
                ('pets_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='loader.pets')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'db_table': 'photos',
            },
        ),
    ]
