# Generated by Django 3.2.10 on 2024-01-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='photos',
            old_name='pets_id',
            new_name='pets',
        ),
        migrations.RemoveField(
            model_name='pets',
            name='photo',
        ),
        migrations.AddField(
            model_name='photos',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
