# Generated by Django 3.2.10 on 2023-12-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20231212_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
