# Generated by Django 3.2.10 on 2023-12-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_message_is_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
