# Generated by Django 3.2.10 on 2023-12-14 21:22

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_message_is_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('type_pet', models.CharField(max_length=25, verbose_name='Вид животного')),
                ('breed', models.CharField(default=None, max_length=25, verbose_name='Порода')),
                ('is_male', models.BooleanField(default=True, verbose_name='Самец')),
                ('photo', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=150)),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': 'Питомцы',
                'db_table': 'pets',
            },
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Минимальная длина имени - 3 символа'), django.core.validators.RegexValidator(code='invalid_name', message='Имя должно содержать только буквы.', regex='^[a-zA-Zа-яА-Я]*$')], verbose_name='Имя'),
        ),
    ]
