# Generated by Django 3.2.10 on 2023-12-18 20:13

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_message_is_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Минимальная длина имени - 3 символа'), django.core.validators.RegexValidator(code='invalid_name', message='Имя должно содержать только буквы.', regex='^[a-zA-Zа-яА-Я]+$')], verbose_name='Имя'),
        ),
    ]
